/* FAQ Service Worker - auto update notification package
   Version is injected from version.json generated by GitHub Actions. */
const CACHE_PREFIX = 'keco-faq-cache';
const CORE_ASSETS = [
  './',
  './index.html',
  './manifest.json',
  './update-notifier.js',
  './version.json'
];

async function getVersion() {
  try {
    const res = await fetch('./version.json', { cache: 'no-store' });
    if (!res.ok) throw new Error('version fetch failed');
    const data = await res.json();
    return data.version || data.commit || String(Date.now());
  } catch (e) {
    return 'fallback-' + Date.now();
  }
}

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const version = await getVersion();
    const cacheName = `${CACHE_PREFIX}-${version}`;
    const cache = await caches.open(cacheName);
    await cache.addAll(CORE_ASSETS.map(url => new Request(url, { cache: 'reload' })));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const version = await getVersion();
    const currentCache = `${CACHE_PREFIX}-${version}`;
    const keys = await caches.keys();
    await Promise.all(keys
      .filter(key => key.startsWith(CACHE_PREFIX) && key !== currentCache)
      .map(key => caches.delete(key))
    );
    await self.clients.claim();
    const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const client of clients) {
      client.postMessage({ type: 'FAQ_UPDATED', version });
    }
  })());
});

self.addEventListener('fetch', event => {
  const req = event.request;
  const url = new URL(req.url);

  // Always fetch version fresh so update detection is not trapped by cache.
  if (url.pathname.endsWith('/version.json')) {
    event.respondWith(fetch(req, { cache: 'no-store' }));
    return;
  }

  // Network-first for HTML so updated pages appear quickly.
  if (req.mode === 'navigate' || req.headers.get('accept')?.includes('text/html')) {
    event.respondWith((async () => {
      try {
        const fresh = await fetch(req, { cache: 'no-store' });
        const cache = await caches.open(`${CACHE_PREFIX}-pages`);
        cache.put(req, fresh.clone());
        return fresh;
      } catch (e) {
        const cached = await caches.match(req);
        return cached || caches.match('./index.html');
      }
    })());
    return;
  }

  // Cache-first fallback for static assets.
  event.respondWith((async () => {
    const cached = await caches.match(req);
    if (cached) return cached;
    const fresh = await fetch(req);
    const cache = await caches.open(`${CACHE_PREFIX}-runtime`);
    cache.put(req, fresh.clone());
    return fresh;
  })());
});
